# Generated by Django 6.1.1 on 2026-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=20, unique='True')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_costo', models.DecimalField(default=0)),
                ('precio_venta', models.DecimalField(default=0)),
                ('iva', models.CharField(choices=[('EXENTO', 'Exento'), ('5', '5%'), ('10', '10%')], max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(choices=[('UNID', 'Unidades'), ('kg', 'Kilogramos')], max_length=10)),
            ],
        ),
    ]
